# Generated by Django 2.2.17 on 2021-01-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='http://codeglider.net'),
            preserve_default=False,
        ),
    ]
