# Generated by Django 2.2.17 on 2021-01-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svod_avails', models.FileField(upload_to='')),
                ('ptv_avails', models.FileField(upload_to='')),
                ('ptv_local_avails', models.FileField(upload_to='')),
                ('screeners', models.FileField(upload_to='')),
                ('ratings', models.FileField(upload_to='')),
            ],
        ),
    ]
